[package]
name = "pocker"
description = "A multithreaded incomplete rewrite of proot, from scratch, just for fun. (The p stands for ptrace)"
version = "0.2.0"
authors = ["Zhongzhi Yu <7296488+markzyu@users.noreply.github.com>"]
repository = "https://github.com/markzyu/pocker"
license = "GPL-3.0-or-later"
edition = "2024"

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pocker-executor = {path = "../executor", version = "0.2"}
pocker-procfs = {path = "../procfs", version = "0.2"}
pocker-ptrace = {path = "../ptrace", version = "0.2"}
pocker-sysaug = {path = "../sysaug", version = "0.2"}
clap = { version = "4", features = ["derive"] }
thiserror = "1.0.25"
tracing = "0.1.26"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3.6", features = ["env-filter"] } 
