[package]
name = "krsm"
version = "0.3.2"
authors = ["Zhongzhi Yu <7296488+markzyu@users.noreply.github.com>"]
description = "This crate is a simple, single threaded, pinned async runtime for futures"
license = "MIT or GPL-3.0-or-later"
repository = "https://github.com/markzyu/pocker/tree/master/krsm/"
edition = "2024"

[lints]
workspace = true

[dependencies]
futures-lite = { version = "2.6.1", default-features = false }
thiserror = { version = "2.0.20", default-features = false }

[dev-dependencies]
crossterm = "0.29.0"
