[package]
name = "pocker-sysaug"
description = "The sysaug crate of pocker -- a multithreaded incomplete rewrite of proot"
version = "0.2.0"
authors = ["Zhongzhi Yu <7296488+markzyu@users.noreply.github.com>"]
repository = "https://github.com/markzyu/pocker"
license = "GPL-3.0-or-later"
edition = "2024"

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pocker-executor = {path = "../executor", version = "0.2"}
krsm = {path = "../krsm", version = "0.3"}
pocker-procfs = {path = "../procfs", version = "0.2"}
pocker-ptrace = {path = "../ptrace", version = "0.2"}
lazy_static = "1.4.0"
libc = "0.2.189"
nix = {version = "0.31.3", features = ["feature", "user"]}
elf = "0.0.10"
futures-lite = "2.6.1"
regex = "1.13.1"
serde_json = "1.0"
serde_regex = "1.2.0"
thiserror = "1.0.25"
tracing = "0.1.26"

[dependencies.serde]
version = "1.0.118"
features = ["derive"]
