# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# While our "example" application has the platform-specific code,
# for simplicity we are compiling and testing everything on the Ubuntu environment only.
# For multi-OS testing see the `cross.yml` workflow.

on: [push, pull_request]

name: Quickstart

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
            target: aarch64-unknown-linux-gnu
          - arch: armv7
            target: armv7-unknown-linux-gnueabihf
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Run cargo check
        run: cross check --target ${{ matrix.target }}

  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
 
      - name: Install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Provide debug info for any failed tests
        run: cat /usr/include/x86_64-linux-gnu/asm/unistd_64.h; echo ===========; cargo run -- --show-syscalls
 
      - name: Run integration tests
        run: RUST_LOG=INFO bash tests.sh

  lints:
    name: Lints and Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
            target: aarch64-unknown-linux-gnu
          - arch: armv7
            target: armv7-unknown-linux-gnueabihf
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
          target: ${{ matrix.target }}

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      
      - name: Run cargo clippy
        run: cargo clippy --workspace --all-targets --tests
      
      - name: Run cargo test
        run: cargo test --workspace --all-targets --tests

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
            target: aarch64-unknown-linux-gnu
          - arch: armv7
            target: armv7-unknown-linux-gnueabihf
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Run cargo build
        run: cross build --target ${{ matrix.target }}
